baseurl: https://chaoming.li
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Chaoming's Blog

# Change it to your Disqus shortname before using
disqusShortname: chaomings-blog

# GA Tracking ID
googleAnalytics: G-MY4GMY6ZN6

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /blog/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 AEST

    sidebar:
        emoji:
        subtitle: Tech entrepreneur, CEO of Insightech.
        avatar:
            enabled: true
            local: true
            src: img/avatar.jpg

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default:

    comments:
        enabled: true
        provider: disqus

        disqusjs:
            shortname: chaomings-blog
            apiUrl: https://disqus.com/api/
            apiKey: cqHBPalxwbSqwr7EYocYpe9AyztvfvSNRBBzLgIPlCBuagxwJvxWDl7GChdlGXWE
            admin: "Chaoming Li"
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        waline:
            serverURL:
            lang:
            pageview:
            emoji:
                - https://unpkg.com/@waline/emojis@1.0.1/weibo
            requiredMeta:
                - name
                - email
                - url
            locale:
                admin: Admin
                placeholder:

        twikoo:
            envId:
            region:
            path:
            lang:

        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: ""

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            site: ChaomingLi
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        toggle: true
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main: []

    social:
        - identifier: linkedin
          name: LinkedIn
          url: https://www.linkedin.com/in/chaomingli/
          params:
              icon: brand-linkedin
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/ChaomingLi
          params:
              icon: brand-twitter
        - identifier: github
          name: GitHub
          url: https://github.com/chaoming
          params:
              icon: brand-github

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100
        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            unsafe: true  # Enable unsafe HTML rendering
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
